import { Heart, Sparkles, Users, Activity, Coins, type LucideIcon } from 'lucide-react';

export type DomainKey = 'self' | 'energy' | 'relationships' | 'health' | 'money';

export interface DomainConfig {
  key: DomainKey;
  label: string;
  emoji: string;
  tagline: string;
  icon: LucideIcon;
  gradient: string; // CSS gradient string
  glow: string;     // box-shadow color
  accentClass: string; // tailwind text-* token
  route: string;
  states: { value: string; label: string; emoji: string; tier: 'low' | 'mid' | 'high' }[];
  resistanceChips: string[];
  bodyOptions: string[];
  softenPrompts: string[];
  affirmations: string[];
  gatherTiers: string[];
  gatherStarters: Record<string, string[]>;
  evidenceCategories: { value: string; label: string; emoji: string }[];
  openingFields: { key: string; label: string; placeholder: string }[];
}

const sharedBody = ['Chest', 'Throat', 'Belly', 'Shoulders', 'Jaw', 'Hands', 'Whole body'];
const sharedSoften = [
  'It makes sense I feel this way.',
  'I can let this be here a moment.',
  'This is allowed to soften at its own pace.',
  'I do not have to fix this right now.',
];
const sharedOpeningFields = [
  { key: 'desire', label: 'Desire', placeholder: 'What do you want?' },
  { key: 'why_it_matters', label: 'Why it matters', placeholder: 'Why does this matter to you?' },
  { key: 'desired_feeling', label: 'Desired feeling', placeholder: 'How do you want to feel?' },
  { key: 'current_resistance', label: 'Current resistance', placeholder: 'What is in the way right now?' },
  { key: 'next_aligned_step', label: 'Next aligned step', placeholder: 'One small step that feels good.' },
];

export const DOMAINS: Record<DomainKey, DomainConfig> = {
  self: {
    key: 'self',
    label: 'Self Current',
    emoji: '🌱',
    tagline: 'Worth, confidence, and the quiet trust of being you.',
    icon: Heart,
    gradient: 'linear-gradient(135deg, hsl(280 50% 60% / 0.2), hsl(330 55% 60% / 0.12))',
    glow: 'hsl(280 50% 60% / 0.3)',
    accentClass: 'text-soul-violet',
    route: '/self',
    states: [
      { value: 'small', label: 'Small', emoji: '🫥', tier: 'low' },
      { value: 'unsure', label: 'Unsure', emoji: '😶', tier: 'low' },
      { value: 'tender', label: 'Tender', emoji: '🤍', tier: 'mid' },
      { value: 'steady', label: 'Steady', emoji: '🌿', tier: 'mid' },
      { value: 'rooted', label: 'Rooted', emoji: '🌳', tier: 'high' },
      { value: 'radiant', label: 'Radiant', emoji: '✨', tier: 'high' },
    ],
    resistanceChips: [
      'I am not enough.', 'I have to prove myself.', 'Who am I to want this?',
      'I should be further along.', 'I am too much.', 'I am not lovable like this.',
      'I always mess this up.',
    ],
    bodyOptions: sharedBody,
    softenPrompts: sharedSoften,
    affirmations: [
      'I am allowed to take up space.',
      'My worth is not earned. It simply is.',
      'I trust who I am becoming.',
      'I am safe to be fully myself.',
      'I belong in my own life.',
      'I am enough exactly as I am right now.',
      'I deserve gentleness from myself.',
      'I am proud of how far I have come.',
      'I let go of who I thought I had to be.',
      'My voice matters. My presence matters.',
      'I am worthy of the life I want.',
      'I am building trust with myself.',
      'I honor the pace of my own becoming.',
      'I love the person I am, today.',
      'I am whole as I am.',
      'I get to choose what I believe about me.',
      'I am allowed to soften.',
      'I am not behind. I am right on time.',
      'My body is a kind home.',
      'I welcome my own presence.',
      'I am someone I can rely on.',
      'I am learning to receive love from myself.',
      'I trust my inner knowing.',
      'I am no longer abandoning myself.',
      'I am free to be at ease in my own skin.',
    ],
    gatherTiers: ['Worthiness', 'Confidence', 'Identity', 'Body & Voice'],
    gatherStarters: {
      Worthiness: [
        'I am worthy without proof.',
        'My existence is enough.',
        'I do not have to earn love.',
        'I am allowed to want what I want.',
      ],
      Confidence: [
        'I trust my next step.',
        'I have everything I need to begin.',
        'I am steady inside myself.',
        'I am allowed to take up space.',
      ],
      Identity: [
        'I am becoming who I am meant to be.',
        'I let old versions of me rest.',
        'I am free to redefine myself.',
        'I get to choose who I am today.',
      ],
      'Body & Voice': [
        'My body is welcome here.',
        'My voice is allowed.',
        'I respect my own pace.',
        'I move at the rhythm that is mine.',
      ],
    },
    evidenceCategories: [
      { value: 'kindness', label: 'Kindness from me', emoji: '🤍' },
      { value: 'wins', label: 'Quiet wins', emoji: '🌱' },
      { value: 'growth', label: 'Signs of growth', emoji: '🌿' },
      { value: 'voice', label: 'I spoke up', emoji: '🗣️' },
    ],
    openingFields: sharedOpeningFields,
  },
  energy: {
    key: 'energy',
    label: 'Energy Current',
    emoji: '⚡',
    tagline: 'Vitality, presence, and a body that feels alive.',
    icon: Activity,
    gradient: 'linear-gradient(135deg, hsl(38 90% 60% / 0.2), hsl(20 85% 60% / 0.12))',
    glow: 'hsl(38 90% 60% / 0.3)',
    accentClass: 'text-amber-400',
    route: '/energy',
    states: [
      { value: 'depleted', label: 'Depleted', emoji: '🪫', tier: 'low' },
      { value: 'foggy', label: 'Foggy', emoji: '🌫️', tier: 'low' },
      { value: 'resting', label: 'Resting', emoji: '🌙', tier: 'mid' },
      { value: 'warming', label: 'Warming', emoji: '🌅', tier: 'mid' },
      { value: 'alive', label: 'Alive', emoji: '🔥', tier: 'high' },
      { value: 'electric', label: 'Electric', emoji: '⚡', tier: 'high' },
    ],
    resistanceChips: [
      'I am too tired.', 'I have nothing left.', 'I should push through.',
      'Resting is lazy.', 'My body is letting me down.', 'I am behind because I am tired.',
    ],
    bodyOptions: sharedBody,
    softenPrompts: sharedSoften,
    affirmations: [
      'My body knows how to restore itself.',
      'Rest is part of my power.',
      'I trust the rhythm my body is in.',
      'Energy returns to me with ease.',
      'I am allowed to slow down.',
      'My presence is a kind of energy.',
      'I receive nourishment from this moment.',
      'My breath is bringing me back.',
      'I am awake to my own life.',
      'Vitality is rising in me.',
      'My body is on my side.',
      'I do not have to force my way alive.',
      'I let new energy in.',
      'I am restored when I let myself be.',
      'Aliveness is my natural state.',
      'I trust the body I am living in.',
      'I am gentle with my engine.',
      'My rest is productive.',
      'I am allowed to feel good in my body.',
      'I am present in this body, in this moment.',
    ],
    gatherTiers: ['Vitality', 'Rest & Recovery', 'Presence', 'Aliveness'],
    gatherStarters: {
      Vitality: [
        'I am alive in this body.',
        'Energy moves through me freely.',
        'I receive what restores me.',
        'My cells know how to thrive.',
      ],
      'Rest & Recovery': [
        'Rest is part of my power.',
        'I am allowed to soften.',
        'My body restores itself with ease.',
        'I do not have to earn rest.',
      ],
      Presence: [
        'I am here, in this moment.',
        'My breath returns me to me.',
        'I land in this body.',
        'I am awake to my own life.',
      ],
      Aliveness: [
        'Aliveness lives in me.',
        'I let life feel good.',
        'I move with my own rhythm.',
        'I am wired for vibrancy.',
      ],
    },
    evidenceCategories: [
      { value: 'rest', label: 'Real rest', emoji: '🌙' },
      { value: 'movement', label: 'Movement', emoji: '🏃' },
      { value: 'aliveness', label: 'Felt aliveness', emoji: '⚡' },
      { value: 'nourishment', label: 'Nourishment', emoji: '🥗' },
    ],
    openingFields: sharedOpeningFields,
  },
  relationships: {
    key: 'relationships',
    label: 'Relationship Current',
    emoji: '🤝',
    tagline: 'Belonging, boundaries, and love that flows both ways.',
    icon: Users,
    gradient: 'linear-gradient(135deg, hsl(340 70% 65% / 0.2), hsl(15 75% 65% / 0.12))',
    glow: 'hsl(340 70% 65% / 0.3)',
    accentClass: 'text-rose-400',
    route: '/relationships',
    states: [
      { value: 'lonely', label: 'Lonely', emoji: '🌧️', tier: 'low' },
      { value: 'guarded', label: 'Guarded', emoji: '🛡️', tier: 'low' },
      { value: 'tender', label: 'Tender', emoji: '🤍', tier: 'mid' },
      { value: 'open', label: 'Open', emoji: '🌷', tier: 'mid' },
      { value: 'connected', label: 'Connected', emoji: '🤝', tier: 'high' },
      { value: 'loved', label: 'Loved', emoji: '💞', tier: 'high' },
    ],
    resistanceChips: [
      'I will be too much.', 'I do not belong here.', 'Love always leaves.',
      'I have to take care of everyone.', 'It is not safe to need people.',
      'No one really sees me.', 'I am hard to love.',
    ],
    bodyOptions: sharedBody,
    softenPrompts: sharedSoften,
    affirmations: [
      'I am safe to be seen.',
      'I belong, even when I am quiet.',
      'I am allowed to need people.',
      'Love is allowed to come close.',
      'I trust the people who love me.',
      'I receive love as easily as I give it.',
      'I am loveable in this exact form.',
      'My honesty is welcome here.',
      'I do not have to earn belonging.',
      'I am allowed to set kind limits.',
      'I attract people who can meet me.',
      'I am safe to let love stay.',
      'My presence is a gift.',
      'I am free to be honest about what I need.',
      'Connection is finding me.',
      'I am held by more than I can see.',
      'I let love be easy.',
      'My boundaries protect my softness.',
      'I am no longer abandoning myself for others.',
      'I belong to my own life first.',
    ],
    gatherTiers: ['Belonging', 'Boundaries', 'Receiving Love', 'Connection'],
    gatherStarters: {
      Belonging: [
        'I belong here, as I am.',
        'My presence is wanted.',
        'I am part of this life.',
        'I am at home in this room.',
      ],
      Boundaries: [
        'My no is loving too.',
        'I am allowed to keep myself safe.',
        'I protect my softness.',
        'I do not abandon myself for closeness.',
      ],
      'Receiving Love': [
        'I let love land.',
        'I am safe to be loved fully.',
        'I receive care without bracing.',
        'Love is allowed to stay.',
      ],
      Connection: [
        'Real connection is finding me.',
        'I am drawn to people who meet me.',
        'I am open to being known.',
        'My honesty makes connection possible.',
      ],
    },
    evidenceCategories: [
      { value: 'kindness', label: 'Kindness received', emoji: '🤍' },
      { value: 'connection', label: 'Real connection', emoji: '🤝' },
      { value: 'boundary', label: 'Held a boundary', emoji: '🛡️' },
      { value: 'reaching-out', label: 'Reached out', emoji: '📩' },
    ],
    openingFields: sharedOpeningFields,
  },
  health: {
    key: 'health',
    label: 'Health Current',
    emoji: '🌿',
    tagline: 'Trust in the body, ease in the cells, wholeness as home.',
    icon: Sparkles,
    gradient: 'linear-gradient(135deg, hsl(160 50% 55% / 0.2), hsl(190 55% 55% / 0.12))',
    glow: 'hsl(160 50% 55% / 0.3)',
    accentClass: 'text-emerald-400',
    route: '/health',
    states: [
      { value: 'unwell', label: 'Unwell', emoji: '🤒', tier: 'low' },
      { value: 'heavy', label: 'Heavy', emoji: '⚖️', tier: 'low' },
      { value: 'mending', label: 'Mending', emoji: '🩹', tier: 'mid' },
      { value: 'easy', label: 'Easy', emoji: '🌿', tier: 'mid' },
      { value: 'vital', label: 'Vital', emoji: '🌞', tier: 'high' },
      { value: 'whole', label: 'Whole', emoji: '🪷', tier: 'high' },
    ],
    resistanceChips: [
      'My body is broken.', 'I cannot trust my body.', 'It will only get worse.',
      'I am behind on healing.', 'My body is the problem.', 'Nothing is working.',
    ],
    bodyOptions: sharedBody,
    softenPrompts: sharedSoften,
    affirmations: [
      'My body is doing its quiet, brilliant work.',
      'Healing happens at its own pace.',
      'I trust my body again, one breath at a time.',
      'My cells know how to mend.',
      'I am safe in my body today.',
      'Ease is allowed to live in me.',
      'My body is on my side.',
      'I am supported by something larger than effort.',
      'Wholeness is my baseline.',
      'I let my body lead.',
      'I am allowed to receive care.',
      'I am not behind in my healing.',
      'My breath is medicine.',
      'I welcome ease into my system.',
      'I trust the wisdom of my body.',
      'Rest is part of my recovery.',
      'My body is a kind home.',
      'I treat myself like someone I love.',
      'Vitality is rising in me.',
      'I am whole, even while I heal.',
    ],
    gatherTiers: ['Trust in Body', 'Healing & Mending', 'Ease', 'Wholeness'],
    gatherStarters: {
      'Trust in Body': [
        'My body is on my side.',
        'I trust my body again.',
        'My body knows how to heal.',
        'I am safe in this body.',
      ],
      'Healing & Mending': [
        'Healing is happening in me.',
        'My cells know how to mend.',
        'I am allowed to recover slowly.',
        'I welcome the medicine of rest.',
      ],
      Ease: [
        'Ease lives in me.',
        'I let my system soften.',
        'My breath returns me to ease.',
        'I am allowed to feel good.',
      ],
      Wholeness: [
        'I am whole as I am.',
        'Wholeness is my baseline.',
        'Nothing about me needs fixing.',
        'I belong in this body.',
      ],
    },
    evidenceCategories: [
      { value: 'rest', label: 'Real rest', emoji: '🌙' },
      { value: 'nourish', label: 'Nourishment', emoji: '🥗' },
      { value: 'movement', label: 'Movement', emoji: '🏃' },
      { value: 'ease', label: 'Felt ease', emoji: '🌿' },
    ],
    openingFields: sharedOpeningFields,
  },
  money: {
    key: 'money',
    label: 'Money Current',
    emoji: '💰',
    tagline: 'Receive freely. Release resistance. Build flow.',
    icon: Coins,
    gradient: 'linear-gradient(135deg, hsl(42 65% 58% / 0.2), hsl(160 30% 40% / 0.12))',
    glow: 'hsl(42 65% 58% / 0.3)',
    accentClass: 'text-soul-gold',
    route: '/money',
    states: [],
    resistanceChips: [],
    bodyOptions: sharedBody,
    softenPrompts: sharedSoften,
    affirmations: [],
    gatherTiers: [],
    gatherStarters: {},
    evidenceCategories: [],
    openingFields: sharedOpeningFields,
  },
};

export const NEW_DOMAIN_KEYS: DomainKey[] = ['self', 'energy', 'relationships', 'health'];
export const ALL_DOMAIN_KEYS: DomainKey[] = ['money', 'self', 'energy', 'relationships', 'health'];
