// Curated wealth affirmations library for Inner Wake.
// Two collections: "Great Wealth" (abundance) and "Effortless Money" (ease/flow).
// Original content authored for Inner Wake.

export const GREAT_WEALTH_AFFIRMATIONS: string[] = [
  "Great wealth arrives in my life with ease and speed, growing in volume, pouring from many directions without pause, serving the good of all, honoring the freedom of everyone, and I keep, share, spend, grow, and move it with pure joy.",
  "Wealth moves toward me without friction, arriving again and again.",
  "Drawing great financial abundance to me is simply part of who I am.",
  "Wealth finds me through paths I anticipate and through paths I never saw coming.",
  "Handling and welcoming great amounts of wealth feels natural and completely right to me.",
  "Wealth reaches me through good and wholesome avenues.",
  "I am worthy of great financial abundance and I welcome it fully into my experience.",
  "My accounts grow richer with every passing day.",
  "Wealth is drawn to me the way iron is drawn to a magnet.",
  "Wealth flows to me around the clock, in rest and in waking.",
  "The things I create and pursue produce enormous financial return.",
  "Creation itself pours financial blessings generously into my life.",
  "Wealth shows up exactly when it is meant to, in perfect order.",
  "Great financial abundance is something I have fully earned the right to receive.",
  "The vibration I carry pulls prosperity toward me without effort.",
  "The wealth that comes to me serves my greatest purpose and deepest wellbeing.",
  "Receiving great wealth fills me with deep and genuine delight.",
  "My growing financial abundance expands my capacity to serve and support the people around me.",
  "My mind and awareness are fully tuned to the presence of great wealth.",
  "Every wave of wealth that enters my life fills me with sincere thankfulness.",
  "The deeper part of my mind draws great wealth to me with absolute precision.",
  "I am certain, down to my core, that great financial abundance belongs to me through sacred right.",
  "The boundless wisdom living inside me guides great wealth through ideal pathways toward me.",
  "I am fully united with the deep riches stored in my inner mind, and money flows to me without resistance.",
  "My inner mind pulls great wealth toward me in this very moment.",
  "I hold deep gratitude for the flawless ways that wealth reaches me.",
  "My inner intelligence is actively guiding great wealth into my daily reality right now.",
  "I fully embrace the truth that great financial abundance is mine through sacred inheritance.",
  "I rest each night in complete peace, knowing that wealth continues moving toward me.",
  "My deeper mind never stops working to bring great wealth into my daily existence.",
  "The boundless wisdom inside me locates great wealth wherever it exists and pulls it directly to me.",
  "I hold with full certainty that great financial abundance already belongs to me.",
  "My trust in the limitless source draws great wealth to me with ease, again and again.",
  "I offer sincere gratitude today for the great wealth that is rightfully and sacredly mine.",
  "Every obstacle that once stood between me and great wealth is cleared from my mind today.",
  "There was a time when great wealth felt far away, and now it comes to me as a matter of course.",
  "My very awareness is the force that draws great financial abundance without any strain.",
  "How extraordinary it is that great wealth flows my way without ceasing.",
  "Receiving great wealth is a posture I hold as my default and natural position.",
  "Within my inner vision, I am already living the full reality of great financial abundance.",
  "I live and breathe the awareness that great abundance is my ordinary condition.",
  "I rewrite my story to declare that great wealth has always come to me freely and without struggle.",
  "Standing in the outcome already achieved, I know that great wealth is already in my hands.",
  "My inner creative power generates great wealth through means far beyond what I can conceive.",
  "I settle into the certainty that great wealth is taking tangible form in my life right now.",
  "At the level of my deepest being, great financial abundance travels with me always.",
  "I am the active creative force pulling great wealth into the life I experience every day.",
  "Great wealth belongs to the sacred awareness that is my truest and deepest nature.",
  "The sense of great wealth rests on me as effortlessly as drawing breath.",
  "Universal principles work flawlessly to deliver great wealth as I hold the inner sense of already being wealthy.",
  "My inner sight shows me great wealth growing more and more with every new day.",
  "I carry within me the awareness that great financial abundance actively searches for me.",
  "The way I simply exist pulls great wealth toward me without any trying.",
  "In the timeless now, I call great wealth forth from the boundless field of all possibility.",
  "Out of the field of pure potential, I pull great wealth into my experience through the power of elevated feeling.",
  "My aligned and open heart draws great wealth from the space where all things are possible.",
  "My intention sends a clear message to the field of creation to bring great wealth into form this very moment.",
  "Outside the limits of space and time, great financial abundance is already my lived reality.",
  "The vibration and resonance I carry draw great wealth to me as a natural outcome.",
  "The union of focused purpose and heightened feeling is how I bring great wealth into my tangible world.",
  "Out of all possible realities, I choose and inhabit the one where great wealth arrives without struggle.",
  "When my thoughts and my heart align, they pull great wealth from the very source of all creation.",
  "I adjust my vibration to match the level where great wealth lives in overflowing supply.",
  "Day by day I grow more and more capable of drawing great financial abundance to me.",
  "My biology answers to the deep belief I carry that great wealth is always on its way.",
  "I am reshaping my inner patterns to embody the kind of person who naturally draws great wealth.",
  "I radiate the feeling of already possessing great wealth outward into the field of creation.",
  "Gratitude is the channel through which I pull great wealth out of the boundless space of all that is possible.",
  "My entire physical being hums with the knowing that great financial abundance is mine.",
  "I step into the version of reality where great wealth is simply how I live.",
  "Through the magnificent weaving of creation itself, great wealth pours into my life in endlessly expanding patterns of plenty.",
  "Great wealth rushes through every layer of possibility and lands squarely in my present experience.",
  "In this astonishing existence, great wealth multiplies and expands throughout every corner of my life.",
  "Through the very structure of aware being, great wealth appears in breathtaking and multidimensional plenty.",
  "My awareness reshapes what is real and great wealth moves through the perfect machinery of the universe into my life.",
  "Within the endless cycle of creation, great wealth spirals toward me with extraordinary and exact timing.",
  "Great wealth makes sudden and powerful jumps directly into my lived experience.",
  "The way a program rewrites its own rules, great wealth surfaces through the very operating system of my life.",
  "Through all the interconnected pathways of potential, great wealth flows into my reality with perfect accuracy.",
  "Bold movement and unshakable conviction are the forces that summon great wealth to me today.",
  "I declare with full authority that great financial abundance comes to me with irresistible momentum.",
  "At full power, I call great wealth into my life with complete and unwavering authority.",
  "I build unstoppable forward force that pulls great wealth to me without delay.",
  "The relentless determination I carry draws great wealth to me with complete and total assurance.",
  "I move with fierce and focused intention and that movement produces great wealth right now.",
  "My limitless vitality draws great financial abundance toward me at every point in time.",
  "The strength and confidence I carry pull great wealth toward me with remarkable swiftness.",
  "I make the firm and irrevocable choice that great wealth pours toward me in this moment.",
  "I shatter every ceiling and receive great financial abundance with total and complete authority.",
  "Operating at my highest level, I naturally call great wealth into the life I am living.",
  "The deep desire and forward momentum I carry draw great wealth toward me without question.",
  "By elevating what I expect and accept, I become an irresistible draw for great wealth today.",
  "I align my whole self to the vibration at which great wealth naturally exists.",
  "I match the frequency that brings great wealth into solid and immediate form.",
  "As the observer of my own life, I bring the possibility of great wealth fully into being in this moment.",
  "Great wealth is drawn to me with a force that cannot be resisted.",
  "Great financial abundance reaches me in a continuous and unbroken stream.",
  "Great wealth is something I have every right to receive and hold.",
  "I stand ready and willing to accept great wealth into my life right now.",
  "My whole being is in complete alignment with the presence of great financial abundance.",
  "Every single day, great wealth is poured into my life as a genuine divine gift.",
  "Receiving great wealth is one of the most natural things about who I am.",
  "I serve as the sacred vessel through which great wealth moves in and through my life.",
  "My daily existence is one of deep and real financial prosperity.",
  "I rejoice in the great wealth that is taking real shape in my life at this very moment.",
  "Great wealth is not something I have; it is something I am.",
  "Sacred guidance is leading me directly toward great financial abundance every single day.",
  "I trust completely in my own power to draw great wealth toward me.",
  "I myself am the wellspring from which great wealth is produced.",
  "Joy and gratitude fill me as great wealth pours toward me with ease and speed, growing in volume, arriving from many places, never stopping, and remaining fully mine.",
  "I can see great financial abundance arriving in my life with total clarity and ease.",
  "Again and again I am amazed at the remarkable ways great wealth shows up in my experience.",
  "Right now, great wealth begins a permanent and easy flow into my life, arriving faster and in ever-growing amounts.",
  "I am the main channel through which great financial abundance moves and circulates.",
  "Great wealth arrives in my life on a steady, unbroken basis from numerous directions and in forms I can see and touch."
];

export const EFFORTLESS_MONEY_AFFIRMATIONS: string[] = [
  "Abundant prosperity floods my life with ease and speed, multiplying from every direction, serving the highest good, and I treasure, share, spend, multiply, and move it with overflowing gratitude and joy.",
  "Wealth comes to me the way water finds its way home, without force and without question.",
  "I draw prosperity toward me with a natural force that requires nothing extra from me.",
  "Prosperity comes looking for me on its own.",
  "Wealth is always eager and willing to make its home in my life.",
  "Prosperity flows toward me during rest, during play, and in every quiet moment of my day.",
  "All of creation works together to place boundless financial doors in my path.",
  "My position in life always places me perfectly for wealth to locate me with ease.",
  "The version of reality I inhabit is one where prosperity arrives fast and without friction.",
  "I have moved fully into the most abundant version of my life where wealth comes without effort.",
  "Wealth arrives in my life without requiring force or struggle.",
  "The life I am living is saturated with wealth that comes simply and freely.",
  "I draw to me the version of life where abundance arrives without any strain.",
  "With each passing moment I settle more deeply into a life where prosperity flows freely.",
  "Every version of lack and effort has melted away, leaving only fullness and plenty.",
  "I am living as the self who knows no ceiling on how much prosperity can arrive.",
  "Accepting abundance that comes without effort is one of my greatest and most natural gifts.",
  "I carry within me the fullness and ease of wealth wherever I go.",
  "Effortless financial plenty is simply how I exist in the world.",
  "I deserve and am fully ready to hold prosperity without any limit.",
  "Across every layer of existence, I pull wealth to me with natural force.",
  "Simply by being who I am, I call prosperity into the space around me.",
  "The field of all creation answers immediately when I hold the awareness that money comes easily.",
  "My whole being vibrates at the exact level where effortless wealth lives.",
  "Prosperity hums through every part of me at the most fundamental level.",
  "Creation takes genuine pleasure in sending wealth to me in ways I never anticipated.",
  "I consistently hold the vibration that matches the peak of financial abundance.",
  "Wealth finds the smoothest and easiest possible path to reach me.",
  "The very structure of existence shifts to make room for effortless wealth to reach me.",
  "Financial openings reveal themselves to me clearly and I step into them with ease.",
  "Wealth arrives through channels I never could have predicted.",
  "Ideal financial openings locate me at exactly the right moment.",
  "Entrances to financial abundance swing open for me before I even reach them.",
  "Achievement and prosperity come to me without requiring force or hardship.",
  "Each inhale brings me into fuller harmony with the flow of effortless wealth.",
  "My financial abundance expands on its own as a natural part of who I am.",
  "Wealth comes to me and I welcome it with open arms and a full heart.",
  "Ease and calm are the conditions in which wealth moves most freely toward me.",
  "Effortless wealth is not something I am reaching for; it is simply what I am.",
  "The life I live is set up to deliver financial abundance without me having to chase it.",
  "I shape the world around me to produce a continuous and limitless supply of wealth.",
  "My awareness generates a never-ending supply of prosperity that flows through my life.",
  "No matter where I look, more wealth is coming my way.",
  "Wealth arrives in my life without friction and without delay.",
  "Financial abundance comes to me freely, requiring nothing difficult from me.",
  "Wealth moves toward me the way everything in nature moves, without force and without fail.",
  "Great wealth lands in my life requiring absolutely nothing hard from me.",
  "Wealth comes to me fast and without any resistance.",
  "Wealth locates me and arrives without exertion on anyone's part.",
  "Financial surprises arrive in my life with ease and I receive them gratefully.",
  "Wealth reaches me through familiar paths and through channels I never imagined.",
  "Whatever I require shows up in my life without effort or complication.",
  "Welcoming and holding great wealth is one of the simplest things I do.",
  "While I rest, wealth continues to move in my direction without pause.",
  "Drawing effortless wealth to me is built into who I am at a foundational level.",
  "Wealth comes to me with speed and without any friction whatsoever.",
  "Favorable openings in life find their way to me without any strain.",
  "Answers and pathways show up in my life even before I have fully formed the question.",
  "My financial life is one of consistent and genuine surplus.",
  "Wealth arrives in my life with precise and extraordinary timing.",
  "Wealth reaches me cleanly and simply, without any confusion or difficulty.",
  "Every situation in my life resolves in exactly the way that serves me best.",
  "Wealth arrives without effort and in quantities that keep growing.",
  "Each day brings financial abundance to me without resistance.",
  "My financial in-flow expands on its own as part of my natural life.",
  "Wealth comes to me without me having to make any special effort to bring it.",
  "Wealth reaches me through channels that delight and astonish me.",
  "Welcoming great financial abundance is something I do with absolute ease.",
  "My financial holdings expand smoothly and organically over time.",
  "Wealth moves toward me without hitting any barrier or obstacle.",
  "Paths of least resistance toward wealth reveal themselves to me as a matter of course.",
  "Blessings and benefits arrive in my life without requiring struggle from me.",
  "Favorable openings that require little effort find their way to me consistently.",
  "Every piece of my life falls into place in ways that consistently serve my good.",
  "Wealth shows up in my life at exactly the right moment, every time.",
  "My position in life is perpetually aligned with the arrival of good things.",
  "Wealth arrives in my life in an atmosphere of peace and complete calm.",
  "Financial abundance flows to me without complication or effort.",
  "Drawing wealth into my daily experience is something I do without difficulty.",
  "Wealth arrives promptly and never keeps me waiting.",
  "My relationship with wealth is marked by ideal and precise timing in every situation.",
  "Effortless wealth is on the move and heading straight to me at this very moment.",
  "Wealth arrives fast and shows up reliably, again and again.",
  "My financial in-flow expands on its own without requiring constant effort from me.",
  "Wealth arrives in my life through means that fill me with genuine pleasure.",
  "Significant amounts of wealth land in my accounts with total ease.",
  "Wealth consistently shows up sooner than I thought it would.",
  "Unexpected surges of wealth are simply part of how my financial life operates.",
  "Favorable and low-effort openings locate me on a consistent, everyday basis.",
  "My financial reserves increase without requiring hard work or strain.",
  "A state of ease and peace is the precise condition in which wealth flows to me most freely.",
  "Each new day delivers financial abundance to me without friction or delay.",
  "Wealth reaches me from every direction and every corner of my life.",
  "Positive reports about my prosperity arrive regularly and without effort.",
  "Wealth arrives exactly when the moment is most right, without fail.",
  "Many different channels of wealth flow into my life with effortless ease.",
  "Wealth picks up speed and arrives more and more swiftly over time.",
  "The choices I make as a matter of natural instinct tend to produce financial gain.",
  "Wealth locates me and arrives without wasting any time.",
  "Wealth comes to me in quantities that exceed what I imagined was possible.",
  "My financial in-flow rises on its own as a natural part of how my life works.",
  "Abundance arrives in my life in greater measure than any need I could have.",
  "The things that bring me joy are the very things through which wealth comes to me.",
  "Every experience and every step in my life opens a door to more financial plenty.",
  "A reliable and consistent flow of wealth is simply part of how my life works.",
  "Entrances to greater prosperity swing open for me without resistance or delay.",
  "Wealth arrives in my life through means that are ideal, fitting, and completely right.",
  "Multiplying my financial in-flow is something that happens for me naturally and without strain.",
  "Wealth comes to me through efforts that feel light and completely aligned with who I am.",
  "Managing and holding greater sums of wealth feels natural and completely comfortable to me.",
  "Financial resources are always within reach for me, available whenever I need them.",
  "The things I give my attention and energy to naturally generate financial return.",
  "With each passing day my experience of living grows lighter and more full of grace.",
  "Consistent financial additions arrive in my accounts with total and effortless ease.",
  "My financial in-flow accelerates, building upon itself with increasing speed.",
  "Answers that require little effort always show up in my life right when I need them."
];

export const ALL_WEALTH_AFFIRMATIONS: string[] = [
  ...GREAT_WEALTH_AFFIRMATIONS,
  ...EFFORTLESS_MONEY_AFFIRMATIONS,
];
